<?php
// actions/download_dashboard_report.php
require_once('../config/database.php');

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Security Check
if (!isset($_SESSION['admin_id'])) {
    header("HTTP/1.1 403 Forbidden");
    exit('Unauthorized access');
}

// 1. Tell the browser to download this as an Excel file (.xls)
$filename = "NC_Garments_Dashboard_Snapshot_" . date('Y-m-d') . ".xls";
header("Content-Type: application/vnd.ms-excel; charset=utf-8");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");

// --- FETCH METRICS ---
$total_sales = 0;
$sales_stmt = $conn->query("SELECT COALESCE(SUM(amount_paid), 0) as total FROM payment WHERE payment_date >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)");
if ($sales_stmt) $total_sales += $sales_stmt->fetch_assoc()['total'];

$retail_stmt = $conn->query("SELECT COALESCE(SUM(total_amount), 0) as total FROM retail_sale WHERE sale_date >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)");
if ($retail_stmt) $total_sales += $retail_stmt->fetch_assoc()['total'];

$active_stmt = $conn->query("SELECT COUNT(*) as count FROM project WHERE status = 'active' AND is_archived = 0");
$active_orders = $active_stmt->fetch_assoc()['count'] ?? 0;

$rec_stmt = $conn->query("
    SELECT 
        (SELECT COALESCE(SUM(agreed_price), 0) FROM project WHERE status = 'active' AND is_archived = 0) - 
        (SELECT COALESCE(SUM(amount_paid), 0) FROM payment pay JOIN project p ON pay.project_id = p.project_id WHERE p.status = 'active' AND p.is_archived = 0) AS total_receivables
");
$receivables = $rec_stmt->fetch_assoc()['total_receivables'] ?? 0;

$low_stmt = $conn->query("
    SELECT 
        (SELECT COUNT(*) FROM premade_product WHERE current_stock <= min_stock_alert AND is_archived = 0) +
        (SELECT COUNT(*) FROM raw_material WHERE current_stock <= min_stock_alert AND is_archived = 0) AS total_low
");
$low_stock = $low_stmt->fetch_assoc()['total_low'] ?? 0;

// --- BUILD THE STYLIZED HTML DOCUMENT ---
// Excel will read this HTML and apply the inline CSS styles to the spreadsheet cells.
echo '<html xmlns:x="urn:schemas-microsoft-com:office:excel">';
echo '<head><meta charset="utf-8"></head>';
echo '<body style="font-family: Arial, sans-serif;">';

// -- HEADER --
echo '<table border="0" cellpadding="5">';
echo '<tr>';
echo '<td colspan="5" style="background-color: #db2777; color: #ffffff; font-size: 24px; font-weight: bold; text-align: center; padding: 15px;">NC GARMENTS ERP</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="5" style="background-color: #fce7f3; color: #db2777; font-size: 14px; font-weight: bold; text-align: center;">Executive Dashboard Summary</td>';
echo '</tr>';
echo '<tr><td colspan="5"></td></tr>'; // Spacer

// -- META INFO --
echo '<tr>';
echo '<td colspan="2" style="font-weight: bold; color: #374151;">Generated By:</td>';
echo '<td colspan="3" style="color: #111827;">' . htmlspecialchars($_SESSION['full_name']) . '</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="2" style="font-weight: bold; color: #374151;">Date Generated:</td>';
echo '<td colspan="3" style="color: #111827;">' . date('F j, Y, g:i A') . '</td>';
echo '</tr>';
echo '<tr><td colspan="5"></td></tr>'; // Spacer

// -- KEY METRICS TABLE --
echo '<tr><td colspan="2" style="background-color: #111827; color: #ffffff; font-weight: bold; font-size: 16px;">Key Performance Metrics</td></tr>';

echo '<tr>';
echo '<td style="background-color: #f9fafb; font-weight: bold; border: 1px solid #e5e7eb;">Total Sales (Last 30 Days)</td>';
echo '<td style="border: 1px solid #e5e7eb; color: #db2777; font-weight: bold;">₱ ' . number_format($total_sales, 2) . '</td>';
echo '</tr>';

echo '<tr>';
echo '<td style="background-color: #f9fafb; font-weight: bold; border: 1px solid #e5e7eb;">Active Custom Orders</td>';
echo '<td style="border: 1px solid #e5e7eb;">' . $active_orders . '</td>';
echo '</tr>';

echo '<tr>';
echo '<td style="background-color: #f9fafb; font-weight: bold; border: 1px solid #e5e7eb;">Outstanding Receivables</td>';
echo '<td style="border: 1px solid #e5e7eb; color: #db2777; font-weight: bold;">₱ ' . number_format($receivables, 2) . '</td>';
echo '</tr>';

echo '<tr>';
echo '<td style="background-color: #f9fafb; font-weight: bold; border: 1px solid #e5e7eb;">Low Stock Alerts</td>';
echo '<td style="border: 1px solid #e5e7eb; color: ' . ($low_stock > 0 ? '#e11d48' : '#059669') . '; font-weight: bold;">' . $low_stock . ' Items</td>';
echo '</tr>';

echo '<tr><td colspan="5"></td></tr>'; // Spacer

// -- UPCOMING DEADLINES TABLE --
echo '<tr><td colspan="5" style="background-color: #111827; color: #ffffff; font-weight: bold; font-size: 16px;">Upcoming Production Deadlines</td></tr>';

echo '<tr>';
echo '<th style="background-color: #db2777; color: #ffffff; border: 1px solid #e5e7eb; width: 250px;">Project Name</th>';
echo '<th style="background-color: #db2777; color: #ffffff; border: 1px solid #e5e7eb; width: 200px;">Client</th>';
echo '<th style="background-color: #db2777; color: #ffffff; border: 1px solid #e5e7eb; width: 100px;">Quantity</th>';
echo '<th style="background-color: #db2777; color: #ffffff; border: 1px solid #e5e7eb; width: 150px;">Due Date</th>';
echo '<th style="background-color: #db2777; color: #ffffff; border: 1px solid #e5e7eb; width: 150px;">Status</th>';
echo '</tr>';

$deadlines_stmt = $conn->query("
    SELECT p.project_name, p.quantity, p.due_date, p.progress, 
           COALESCE(c.full_name, 'Internal Restock') as client_name
    FROM project p
    LEFT JOIN customer c ON p.customer_id = c.customer_id
    WHERE p.status = 'active' AND p.is_archived = 0
    ORDER BY p.due_date ASC
");

if ($deadlines_stmt && $deadlines_stmt->num_rows > 0) {
    while ($row = $deadlines_stmt->fetch_assoc()) {
        echo '<tr>';
        echo '<td style="border: 1px solid #e5e7eb; font-weight: bold;">' . htmlspecialchars($row['project_name']) . '</td>';
        echo '<td style="border: 1px solid #e5e7eb;">' . htmlspecialchars($row['client_name']) . '</td>';
        echo '<td style="border: 1px solid #e5e7eb; text-align: center;">' . $row['quantity'] . '</td>';
        echo '<td style="border: 1px solid #e5e7eb; text-align: center; color: #e11d48; font-weight: bold;">' . date('M j, Y', strtotime($row['due_date'])) . '</td>';
        echo '<td style="border: 1px solid #e5e7eb; text-align: center; font-weight: bold;">' . strtoupper($row['progress']) . '</td>';
        echo '</tr>';
    }
} else {
    echo '<tr><td colspan="5" style="border: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-style: italic;">No active deadlines at this time.</td></tr>';
}

echo '</table>';
echo '</body></html>';
exit();