<?php
// actions/export_ledger.php
require_once('../config/database.php');

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Security Check: Must be Admin or Superadmin
if (!isset($_SESSION['admin_id']) || !in_array($_SESSION['role'], ['admin', 'superadmin'])) {
    header("HTTP/1.1 403 Forbidden");
    exit('Unauthorized access');
}

// 1. Capture Filtering Parameters
$start_date = $_GET['start'] ?? date('Y-m-01');
$end_date = $_GET['end'] ?? date('Y-m-d');
$end_date_inclusive = $end_date . ' 23:59:59';

// 2. Set Excel Download Headers
$filename = "NC_Garments_Master_Ledger_{$start_date}_to_{$end_date}.xls";

header("Content-Type: application/vnd.ms-excel; charset=utf-8");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");

// 3. Output the Styled HTML Document
echo '<html xmlns:x="urn:schemas-microsoft-com:office:excel">';
echo '<head><meta charset="utf-8"></head>';
echo '<body style="font-family: Arial, sans-serif;">';

// -- HEADER SECTION --
echo '<table border="0" cellpadding="6" cellspacing="0">';
echo '<tr>';
echo '<td colspan="8" style="background-color: #db2777; color: #ffffff; font-size: 24px; font-weight: bold; text-align: center; padding: 15px;">NC GARMENTS ERP</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="8" style="background-color: #fce7f3; color: #db2777; font-size: 14px; font-weight: bold; text-align: center;">Master Financial Ledger (Projects & Retail)</td>';
echo '</tr>';
echo '<tr><td colspan="8"></td></tr>'; // Spacer

// -- META INFO SECTION --
echo '<tr>';
echo '<td colspan="2" style="font-weight: bold; color: #374151;">Generated By:</td>';
echo '<td colspan="6" style="color: #111827;">' . htmlspecialchars($_SESSION['full_name']) . '</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="2" style="font-weight: bold; color: #374151;">Date Generated:</td>';
echo '<td colspan="6" style="color: #111827;">' . date('F j, Y, g:i A') . '</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="2" style="font-weight: bold; color: #374151;">Reporting Period:</td>';
echo '<td colspan="6" style="color: #111827;">' . date('M j, Y', strtotime($start_date)) . ' to ' . date('M j, Y', strtotime($end_date)) . '</td>';
echo '</tr>';
echo '<tr><td colspan="8"></td></tr>'; // Spacer

// -- DATA TABLE HEADERS --
echo '<tr>';
echo '<th style="background-color: #111827; color: #ffffff; border: 1px solid #e5e7eb; width: 150px;">Date & Time</th>';
echo '<th style="background-color: #111827; color: #ffffff; border: 1px solid #e5e7eb; width: 120px;">Source</th>';
echo '<th style="background-color: #111827; color: #ffffff; border: 1px solid #e5e7eb; width: 120px;">Reference No.</th>';
echo '<th style="background-color: #111827; color: #ffffff; border: 1px solid #e5e7eb; width: 250px;">Client Name</th>';
echo '<th style="background-color: #111827; color: #ffffff; border: 1px solid #e5e7eb; width: 250px;">Description / Item</th>';
echo '<th style="background-color: #111827; color: #ffffff; border: 1px solid #e5e7eb; width: 120px;">Payment Method</th>';
echo '<th style="background-color: #111827; color: #ffffff; border: 1px solid #e5e7eb; width: 180px;">Processed By</th>';
echo '<th style="background-color: #111827; color: #ffffff; border: 1px solid #e5e7eb; width: 120px; text-align: right;">Amount (PHP)</th>';
echo '</tr>';

// 4. Query the Database (COMBINED UNION ALL)
$total_revenue = 0;

$stmt = $conn->prepare("
    SELECT 
        p.payment_date as txn_date,
        p.reference_number,
        p.payment_method,
        p.amount_paid as total_amount,
        prj.project_id as ref_id,
        prj.project_name as item_name,
        COALESCE(c.full_name, 'Internal / Walk-in') as client_name,
        a.full_name as processed_by,
        'Project' as source_type
    FROM payment p
    JOIN project prj ON p.project_id = prj.project_id
    LEFT JOIN customer c ON prj.customer_id = c.customer_id
    LEFT JOIN admin a ON p.processed_by_admin = a.admin_id
    WHERE p.payment_date BETWEEN ? AND ?

    UNION ALL

    SELECT 
        rs.sale_date as txn_date,
        rs.reference_number,
        rs.payment_method,
        rs.total_amount,
        rs.sale_id as ref_id,
        'POS Retail Sale' as item_name,
        COALESCE(c.full_name, 'Walk-in Customer') as client_name,
        a.full_name as processed_by,
        'Retail' as source_type
    FROM retail_sale rs
    LEFT JOIN customer c ON rs.customer_id = c.customer_id
    LEFT JOIN admin a ON rs.processed_by_admin = a.admin_id
    WHERE rs.sale_date BETWEEN ? AND ?

    ORDER BY txn_date ASC
");

// Bind start and end date twice (once for the first query, once for the second)
$stmt->bind_param("ssss", $start_date, $end_date_inclusive, $start_date, $end_date_inclusive);
$stmt->execute();
$result = $stmt->get_result();

// 5. Output Rows
if ($result && $result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $total_revenue += $row['total_amount'];
        $date_formatted = date('M d, Y h:i A', strtotime($row['txn_date']));
        
        $is_project = ($row['source_type'] === 'Project');
        $prefix = $is_project ? '#PRJ-' : '#SALE-';
        $source_label = $is_project ? 'Custom Order' : 'Store POS';
        $source_color = $is_project ? '#6366f1' : '#db2777'; // Blue for projects, Pink for retail
        
        $full_item_desc = $prefix . str_pad($row['ref_id'], 4, '0', STR_PAD_LEFT) . " - " . htmlspecialchars($row['item_name']);
        
        echo '<tr>';
        echo '<td style="border: 1px solid #e5e7eb;">' . $date_formatted . '</td>';
        echo '<td style="border: 1px solid #e5e7eb; font-weight: bold; text-align: center; color: ' . $source_color . ';">' . $source_label . '</td>';
        echo '<td style="border: 1px solid #e5e7eb; text-align: center;">' . htmlspecialchars($row['reference_number'] ?: 'N/A') . '</td>';
        echo '<td style="border: 1px solid #e5e7eb; font-weight: bold;">' . htmlspecialchars($row['client_name']) . '</td>';
        echo '<td style="border: 1px solid #e5e7eb;">' . $full_item_desc . '</td>';
        echo '<td style="border: 1px solid #e5e7eb; text-align: center; text-transform: uppercase;">' . htmlspecialchars($row['payment_method']) . '</td>';
        echo '<td style="border: 1px solid #e5e7eb;">' . htmlspecialchars($row['processed_by']) . '</td>';
        echo '<td style="border: 1px solid #e5e7eb; text-align: right; color: #059669; font-weight: bold;">' . number_format($row['total_amount'], 2) . '</td>';
        echo '</tr>';
    }
} else {
    echo '<tr><td colspan="8" style="border: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-style: italic; padding: 20px;">No transactions found for this period.</td></tr>';
}

// 6. Output Footer Totals
echo '<tr>';
echo '<td colspan="7" style="border: 1px solid #e5e7eb; text-align: right; font-weight: bold; background-color: #f9fafb; font-size: 14px;">TOTAL COMBINED REVENUE:</td>';
echo '<td style="border: 1px solid #e5e7eb; text-align: right; font-weight: bold; background-color: #fce7f3; color: #db2777; font-size: 16px;">₱ ' . number_format($total_revenue, 2) . '</td>';
echo '</tr>';

echo '</table>';
echo '</body></html>';
exit();